# Generated by Django 2.0.6 on 2018-08-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0003_auto_20180610_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrations',
            name='pdf_of_Calibration_Sheet',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='calibrations',
            name='pdf_of_Instructions',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
