# Generated by Django 2.0.6 on 2018-06-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_List', models.CharField(choices=[('TL', 'TL'), ('BA', 'BA'), ('SV', 'SV'), ('CM', 'CM'), ('CS', 'CS'), ('SS', 'SS'), ('MA', 'MA')], default=None, max_length=256)),
                ('Inventory_Number', models.CharField(default=None, max_length=200)),
                ('Manufacturer', models.CharField(default=None, max_length=200)),
                ('Model_Number', models.CharField(default=None, max_length=200)),
                ('Serial_Number', models.CharField(default=None, max_length=200)),
                ('Calibration_Date', models.DateField()),
                ('Due_Date', models.DateField(verbose_name='Calibration Due Date')),
                ('Calibration_Frequency', models.IntegerField()),
                ('Days_To_Calibration', models.IntegerField()),
                ('Current_Status', models.CharField(choices=[('Need to be Repaired', 'Need to be Repaired'), ('In Service', 'In Service'), ('Out of Service', 'Out of Service')], default=None, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
