# Generated by Django 2.0.6 on 2018-06-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180609_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Inventory_Tag',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Equipment_List',
            field=models.CharField(choices=[('TL', 'Tool'), ('BARBA', 'BA'), ('Sieve', 'SV'), ('Compaction Mold', 'CM'), ('Cool dude', 'CS'), ('Soundness Sieve', 'SS'), ('Marshall Apparatus', 'MA')], default=None, max_length=256),
        ),
    ]
