# Generated by Django 2.0.6 on 2018-06-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180609_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Inventory_Tag',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
