# Generated by Django 2.0.6 on 2018-06-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180609_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Inventory_Tag',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
