# Generated by Django 2.0.6 on 2018-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180609_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Inventory_Tag',
            field=models.CharField(blank=True, default=None, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
