# Generated by Django 2.0.6 on 2018-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180609_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Condition_as_recieved',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Inventory_Tag',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
