# Generated by Django 2.0.6 on 2018-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180609_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Condition_as_recieved',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default=None, max_length=10),
        ),
    ]
