# Generated by Django 2.0.6 on 2018-06-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20180609_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='pdf',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Calibration_Frequency',
            field=models.IntegerField(help_text='months'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Inventory_Tag',
            field=models.CharField(default='<Equipment Type>-<Inventory Number>', max_length=20),
        ),
    ]
