# Generated by Django 2.0.6 on 2018-06-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20180609_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='Days_To_Calibration',
        ),
    ]
