# Generated by Django 2.0.6 on 2018-06-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_equipment_days_to_calibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Days_To_Calibration',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
