# Generated by Django 2.0.6 on 2018-08-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_equipment_days_to_calibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Location_In_Lab',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
