# Generated by Django 2.0.6 on 2018-08-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_equipment_location_in_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='Days_To_Calibration',
        ),
    ]
