# Generated by Django 2.0.6 on 2018-08-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_equipment_days_to_calibration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='pdf',
        ),
        migrations.AddField(
            model_name='equipment',
            name='pdf_1',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pdf_2',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pdf_3',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pdf_4',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pdf_5',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pdf_6',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
