# Generated by Django 2.0.6 on 2018-08-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20180804_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='pdf_1',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
