# Generated by Django 2.0.6 on 2018-08-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20180804_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='pdf_1',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pdf_2',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pdf_3',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pdf_4',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pdf_5',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pdf_6',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
