# Generated by Django 2.0.6 on 2018-08-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20180804_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Inventory_Tag',
            field=models.CharField(default='<Equipment Type>-<Inventory Number>', max_length=20, unique=True),
        ),
    ]
