# Generated by Django 2.0.6 on 2018-08-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20180804_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='Equipment_List',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='Inventory_Number',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Inventory_Tag',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
