# Generated by Django 2.0.6 on 2018-08-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20180804_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Equipment_List',
            field=models.CharField(choices=[('TL', 'Tool'), ('BA', 'BARBA'), ('Sieve', 'SV'), ('Compaction Mold', 'CM'), ('Cool dude', 'CS'), ('Soundness Sieve', 'SS'), ('Marshall Apparatus', 'MA')], default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='equipment',
            name='Inventory_Number',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
