# Generated by Django 2.0.6 on 2018-08-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20180804_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Equipment_List',
            field=models.CharField(choices=[('TL', 'Tool'), ('BA', 'BARBA'), ('SV', 'Sieve'), ('CM', 'Compaction MoOld'), ('CS', 'Cold Stone'), ('SS', 'Soundness Sieve'), ('MA', 'Marshall Aparatus')], default=None, max_length=256),
        ),
    ]
