# Generated by Django 2.0.6 on 2018-08-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20180805_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Equipment_List',
            field=models.CharField(choices=[('Tool', 'TL'), ('BA', 'BA'), ('Sieve', 'SV'), ('CompactionMold', 'CM'), ('Cleanness Sieve', 'CS'), ('Soundness Sieve', 'SoS'), ('Marshall Aaparatus', 'MA'), ('Slump Set', 'SS'), ('Slump set thermometer', 'SST')], default=None, max_length=256),
        ),
    ]
