# Generated by Django 2.0.6 on 2018-08-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20180808_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Description_of_Item',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Current_Status',
            field=models.CharField(choices=[('On Lease', 'On Lease'), ('Missing', 'Missing'), ('Need to be Repaired', 'Need to be Repaired'), ('In Service', 'In Service'), ('Out of Service', 'Out of Service')], default=None, max_length=200),
        ),
    ]
