# Generated by Django 2.0.6 on 2018-08-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20180808_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Description_of_Item',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
