# Generated by Django 2.0.6 on 2018-08-08 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20180808_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='Description_of_Item',
        ),
    ]
