# Generated by Django 2.0.6 on 2018-08-08 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_equipment_description_of_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='Description_of_Item',
        ),
    ]
