# Generated by Django 2.0.6 on 2018-08-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_remove_equipment_description_of_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Description_of_Item',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
