# Generated by Django 2.0.6 on 2018-08-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_equipment_description_of_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Equipment_List',
            field=models.CharField(choices=[('Tool', 'Tool'), ('BA', 'BA'), ('Sieve', 'Sieve'), ('Compaction Mold', 'Compaction Mold'), ('Cleanness Sieve', 'Cleanness Sieve'), ('Soundness Sieve', 'Soundness Sieve'), ('Marshall Aaparatus', 'Marshall Aparatus'), ('Slump Set', 'Slump Set'), ('Slump set thermometer', 'Slump Set Thermometer')], default=None, max_length=256),
        ),
    ]
