# Generated by Django 2.0.6 on 2018-09-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20180825_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='pdf_1',
            new_name='pdf_of_calibration_1',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='pdf_2',
            new_name='pdf_of_calibration_2',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='pdf_3',
            new_name='pdf_of_calibration_3',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='pdf_4',
            new_name='pdf_of_calibration_4',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='pdf_5',
            new_name='pdf_of_calibration_5',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='pdf_6',
            new_name='pdf_of_introduction_to_inventory',
        ),
    ]
